### ISSUE TITLE
itemAdded / itemRemoved

### ISSUE THREAD

**Issue by bernhardberger** [gallyamow/vue2-muuri#12]
https://github.com/gallyamow/vue2-muuri/blob/6f55dbf8fe2f377e94c9343d4b8c192c5ceb2f39/src/components/MGrid.vue#L306

Hi, thanks for making your implementation public, it helped me with some details when I integrated Muuri in one of my Vue projects.

However: what dies that comment mean? I tried translating it, but the translated text didn't make sense.

Thank you!

**Comment by gallyamow** [comment]
Hi, I'm glad that you found lib useful. The comment means "Should I use remove before add?". Sorry, I wrote the comment with some mistake that's why I couldn't translate it.
